services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Smichaelsen\Noti\Event\EventRegistry:
    public: true

  Smichaelsen\Noti\Event\LogEntry:
    tags:
      - name: noti.event

  Smichaelsen\Noti\Backend\Toolbar\:
    resource: '../Classes/Backend/Toolbar/*'
    public: true

  Smichaelsen\Noti\Hook\:
    resource: '../Classes/Hook/*'
    public: true

  Smichaelsen\Noti\Log\:
    resource: '../Classes/Log/*'
    public: true

  Smichaelsen\Noti\Service\:
    resource: '../Classes/Service/*'
    public: true

  Smichaelsen\Noti\Service\NotificationService:
    tags:
      - name: event.listener
        identifier: 'NotiNotificationService'
        event: Smichaelsen\Noti\Event\EventInterface
