services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Smichaelsen\Noti\:
    resource: '../Classes/*'
    public: true
    exclude:
      - '../Classes/CompilerPass'
      - '../Classes/Event'

  Smichaelsen\Noti\Event\LogEntry:
    tags:
      - name: noti.event

  Smichaelsen\Noti\Notifier\EmailNotifier:
    tags:
      - name: noti.notifier
        label: E-Mail

  Smichaelsen\Noti\Notifier\NotificationCenterNotifier:
    tags:
      - name: noti.notifier
        label: TYPO3

  Smichaelsen\Noti\Service\NotificationService:
    tags:
      - name: event.listener
        identifier: 'NotiNotificationService'
        event: Smichaelsen\Noti\Event\EventInterface
